### ISSUE TITLE
Unable to install truecrack

### ISSUE THREAD

**Issue by overdrivemachines** [MarkRijckenberg/shell-scripts#1]
I was following your cuda-java-truecrack-python-pip-install.bash
When I run sudo make (line 45), I get the error:
nvcc fatal   : Unknown option '-opencc-options'

Any suggestions how I can fix this?

**Comment by MarkRijckenberg** [comment]
I see a similar error message here:   https://github.com/lvaccaro/truecrack/issues/40     Are you testing my procedure in Mac OS X? Which version of which operating system are you using to run the install script? I only tested the procedure in Ubuntu 14.04 LTS 64-bit.....

**Comment by overdrivemachines** [comment]
Im using Ubuntu 14.04.3 LTS 64bit. My error in https://github.com/lvaccaro/truecrack/issues/40 is similar to j3ernhard. However j3ernhard is using OSX and I am using Ubuntu.
Please help I need to use Trucrack for a project asap.

**Comment by MarkRijckenberg** [comment]
This looks like an issue with the truecrack source code on Github. As a workaround, I suggest trying to compile truecrypt without enabling the GPU (CPU only) so that nvcc is not used. This means running 'sudo ./configure --enable-cpu'  before running 'sudo make'   

 According to the following page  
http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#axzz40SxGuU4A
--opencc-options is not a valid command line option (anymore?) for nvcc.

If you still want to try to compile using nvcc, I suggest running this command:
grep opencc ~/truecrack/src/*

Remove the offending command line option   --opencc-options -OPT:Olimit=0   in each of the following files:
~/truecrack/src/Makefile:   $(COMPILER) -c Cuda.cu $(CFLAGS) --opencc-options -OPT:Olimit=0 $< -o $@
~/truecrack/src/Makefile.am:        $(COMPILER) -c Cuda.cu $(CFLAGS) --opencc-options -OPT:Olimit=0 $< -o $@
~/truecrack/src/Makefile.in:          $(COMPILER) -c Cuda.cu $(CFLAGS) --opencc-options -OPT:Olimit=0 $< -o $@

Save the changes to those 3 files. Then retry compiling.

I have not tested this nvcc related procedure myself. So I am not sure it will work.

**Comment by MarkRijckenberg** [comment]
Closing issue, as there has been no further communication about this issue for more than a year.
